package br.eti.gadelha.persistence.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

import javax.persistence.*;
import java.util.Date;

@Audited @AuditTable(value = "shipsynop_auditoria")
@Entity @Table(name="shipsynop")//, schema="shipsynopweb")
@AllArgsConstructor @NoArgsConstructor @EqualsAndHashCode(callSuper = false) @Data
public class ShipSynop extends GenericEntity {

    private String observador;
    @Temporal(TemporalType.TIMESTAMP)
    private Date dataObservacao;
    private String estacao;
    private String iw;
    private String iii;
    private String ir;
    private String ix;
    private String h;
    private String dd;
    private String ff;
    private String fixo00_1;
    private String fff;
    private String fixo1_1;
    private String fixo2_1;
    private String fixo3_1;
    private String fixo4_1;
    private String fixo5_1;
    private String a;
    private String ppp;
    private String fixo6_1;
    private String tr;
    private String fixo7_1;
    private String ww;
    private String fixo8_1;
    private String fixo9_1;
    private String fixo222_2;
    private String fixo0_2;
    private String fixo1_2;
    private String fixo2_2;
    private String fixo3_2;
    private String dw1dw1;
    private String dw2dw2;
    private String fixo4_2;
    private String fixo5_2;
    private String fixo6_2;
    private String fixo70_2;
    private String fixo8_2;
    private String ci;
    private String bi;
    private String zi;
    private String fixo_333;
    private String fixo1_3;
    private String fixo2_3;
    private String fixo5_3;
    private String ind89;
    private String fixo555_5;
    private String iChw;
    private String iCM;
    private String cs;
    private String iCF;
    private String iCP;
    private String iCQ;
    private String _2snTdTdTdUUU;
    private String _5Pw2Pw2Hw2Hw2;
    private String _8NhClCmCh;
    private String dddddd;
    private String _2PwPwHwHw;
    private String _00fff;
    private String _3PoPoPoPo;
    private String _2snTnTnTn;
    private String yyggiw;
    private String _1snTTT;
    private String _5appp;
    private String _6RRRtr;
    private String _222DsVs;
    private String _4Pw1Pw1Hw1Hw1;
    private String irixhVV;
    private String iiiii;
    private String _99LaLaLa;
    private String qcLoLoLoLo;
    private String _3dw1dw1dw2dw2;
    private String _6IsEsEsRs;
    private String nddff;
    private String _4PPPP;
    private String _1PwaPwaHwaHwa;
    private String _70HwaHwaHwa;
    private String _7wwW1W2;
    private String ciSibiDizi;
    private String ice;
    private String _1snTxTxTx;
    private String _0SsTwTwTw;
    private String _8SwTbTbTb;
    private String yy;
    private String fixo99;
    private String laLaLa;
    private String qc;
    private String ii;
    private String loLoLoLo;
    private String vv;
    private String aabbxx;
    private String gg;
    private String poPoPoPo;
    private String ch;
    private String tdTdTd_UUU;
    private String n;
    private String sn1_1;
    private String ttt;
    private String rrr;
    private String pppp;
    private String w1W2;
    private String nh;
    private String sn2_1;
    private String cl;
    private String cm;
    private String hw1Hw1;
    private String pw2Pw2;
    private String hwHw;
    private String ss;
    private String pwaPwa;
    private String pw1Pw1;
    private String vs;
    private String _is;
    private String gggg;
    private String ds;
    private String twTwTw;
    private String hwaHwa;
    private String pwPw;
    private String hw2Hw2;
    private String esEs;
    private String sw;
    private String sn2_3;
    private String di;
    private String hwa2Hwa2Hwa2;
    private String p24P24P24;
    private String tnTnTn;
    private String _9GGgg;
    private String sn1_3;
    private String si;
    private String tbTbTb;
    private String txTxTx;
    private String rs;
    private boolean ship;
    private boolean synop;
    private String iChwiCMCsiCFiCpiCQ;
    private String _5ind89P24P24P24;

    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.REFRESH)
    @JoinColumn(name = "file", nullable = true)
    private File file;
}